version: '3'
services:
  node-serveur:
    container_name: serveur
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      - Pi-Cloud
    environment:
      - MONGODB_HOST=mongodb
    deploy:
      mode: global 

  mongodb:
    container_name: mongo
    image: mongo:4.4.0
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries : 5
      start_period: 5s
    networks:
      - Pi-Cloud

networks:
  Pi-Cloud:
    driver: bridge
    
volumes:
  mongoDB:
