version: '3'
services:
  node-serveur:
    container_name: serveur
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      - Pi-Cloud
    deploy:
      mode: global 
  mongodb :
    container_name: mongo
    image: mongo:latest
    networks:
      - Pi-Cloud

networks:
  Pi-Cloud:
    driver: bridge

