version: '3'
services:
  node-server:
    build:
      context: ./Node-
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongodata:
