version: '3'
services:
  node-serveur:
    container_name: serveur
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - postgreSQL
    networks:
      - Pi-Cloud
    deploy:
      mode: global 

  mongodb :
    container_name: mongo
    image: mongo:latest
    networks:
      - Pi-Cloud
    ports:
      - "27017:27017"

  postgreSQL :
    container_name: postgres
    image: postgres:15.4
    networks:
      - Pi-Cloud
    environment:
      - POSTGRES_PASSWORD=superadmin
      #- POSTGRES_DB=Pi_Cloud
    volumes:
      - ./databases/initialisation/postgreSQL/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 5432:5432

networks:
  Pi-Cloud:
    driver: bridge

